//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TileMapEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TileMapEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AboutBackground {
            get {
                object obj = ResourceManager.GetObject("AboutBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AboutPluginBackground {
            get {
                object obj = ResourceManager.GetObject("AboutPluginBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AboutSide {
            get {
                object obj = ResourceManager.GetObject("AboutSide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditClearSelection {
            get {
                object obj = ResourceManager.GetObject("EditClearSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditDelete {
            get {
                object obj = ResourceManager.GetObject("EditDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditInvertSelection {
            get {
                object obj = ResourceManager.GetObject("EditInvertSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditMakeTileBrush {
            get {
                object obj = ResourceManager.GetObject("EditMakeTileBrush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditManageTileBrushes {
            get {
                object obj = ResourceManager.GetObject("EditManageTileBrushes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditRedo {
            get {
                object obj = ResourceManager.GetObject("EditRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditSelectAll {
            get {
                object obj = ResourceManager.GetObject("EditSelectAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditUndo {
            get {
                object obj = ResourceManager.GetObject("EditUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileNew {
            get {
                object obj = ResourceManager.GetObject("FileNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileOpen {
            get {
                object obj = ResourceManager.GetObject("FileOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileOpenRecent {
            get {
                object obj = ResourceManager.GetObject("FileOpenRecent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilePageSetup {
            get {
                object obj = ResourceManager.GetObject("FilePageSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilePrint {
            get {
                object obj = ResourceManager.GetObject("FilePrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilePrintPreview {
            get {
                object obj = ResourceManager.GetObject("FilePrintPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileSave {
            get {
                object obj = ResourceManager.GetObject("FileSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileSaveAs {
            get {
                object obj = ResourceManager.GetObject("FileSaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpAbout {
            get {
                object obj = ResourceManager.GetObject("HelpAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] HelpAboutDialog {
            get {
                object obj = ResourceManager.GetObject("HelpAboutDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpCommandReference {
            get {
                object obj = ResourceManager.GetObject("HelpCommandReference", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpContents {
            get {
                object obj = ResourceManager.GetObject("HelpContents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] HelpDialogBoxReference {
            get {
                object obj = ResourceManager.GetObject("HelpDialogBoxReference", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpEditCommandReference {
            get {
                object obj = ResourceManager.GetObject("HelpEditCommandReference", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpFeatures {
            get {
                object obj = ResourceManager.GetObject("HelpFeatures", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpFileCommandReference {
            get {
                object obj = ResourceManager.GetObject("HelpFileCommandReference", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpGettingStarted {
            get {
                object obj = ResourceManager.GetObject("HelpGettingStarted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpHelpCommandReference {
            get {
                object obj = ResourceManager.GetObject("HelpHelpCommandReference", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpIndex {
            get {
                object obj = ResourceManager.GetObject("HelpIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///10
        ///a
        ///accordingly
        ///all
        ///allow
        ///allowed
        ///allows
        ///also
        ///an
        ///and
        ///any
        ///application
        ///arbitrary
        ///are
        ///as
        ///assigned
        ///at
        ///automatically
        ///available
        ///be
        ///before
        ///between
        ///by
        ///can
        ///categories
        ///clears
        ///com
        ///convenience
        ///copied
        ///copies
        ///creation
        ///current
        ///currently
        ///cuts
        ///deletion
        ///delineate
        ///desired
        ///discarded
        ///displayed
        ///distinct
        ///each
        ///editing
        ///executes
        ///except
        ///exception
        ///exits
        ///extensive
        ///facilitate
        ///facilitates
        ///fall
        ///first
        ///for
        ///from
        ///functions
        ///further
        ///getting
        ///gives
        ///google
        ///grouped
        ///http
        ///if
        ///in
        ///into
        ///i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpKeywordBlacklist {
            get {
                return ResourceManager.GetString("HelpKeywordBlacklist", resourceCulture);
            }
        }
        
        internal static byte[] HelpLayerCommandReference {
            get {
                object obj = ResourceManager.GetObject("HelpLayerCommandReference", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpLayerPropertiesDialog {
            get {
                object obj = ResourceManager.GetObject("HelpLayerPropertiesDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpMapCommandReference {
            get {
                object obj = ResourceManager.GetObject("HelpMapCommandReference", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpMapPropertiesDialog {
            get {
                object obj = ResourceManager.GetObject("HelpMapPropertiesDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpMapStatisticsDialog {
            get {
                object obj = ResourceManager.GetObject("HelpMapStatisticsDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpPluginCommandReference {
            get {
                object obj = ResourceManager.GetObject("HelpPluginCommandReference", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpPluginInfoDialog {
            get {
                object obj = ResourceManager.GetObject("HelpPluginInfoDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpSearch {
            get {
                object obj = ResourceManager.GetObject("HelpSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] HelptIDE {
            get {
                object obj = ResourceManager.GetObject("HelptIDE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpTileSheetCommandReference {
            get {
                object obj = ResourceManager.GetObject("HelpTileSheetCommandReference", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpTileSheetPropertiesDialog {
            get {
                object obj = ResourceManager.GetObject("HelpTileSheetPropertiesDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelpViewCommandReference {
            get {
                object obj = ResourceManager.GetObject("HelpViewCommandReference", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageBackground {
            get {
                object obj = ResourceManager.GetObject("ImageBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Layer {
            get {
                object obj = ResourceManager.GetObject("Layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerBringForward {
            get {
                object obj = ResourceManager.GetObject("LayerBringForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerDelete {
            get {
                object obj = ResourceManager.GetObject("LayerDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerInvisible {
            get {
                object obj = ResourceManager.GetObject("LayerInvisible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerNew {
            get {
                object obj = ResourceManager.GetObject("LayerNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerProperties {
            get {
                object obj = ResourceManager.GetObject("LayerProperties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerSendBackward {
            get {
                object obj = ResourceManager.GetObject("LayerSendBackward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerVisible {
            get {
                object obj = ResourceManager.GetObject("LayerVisible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Reciprocal License (Ms-RL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///
        ///A &quot;contributor&quot; is any person that distributes its contribu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Map {
            get {
                object obj = ResourceManager.GetObject("Map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MapProperties {
            get {
                object obj = ResourceManager.GetObject("MapProperties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MapStatistics {
            get {
                object obj = ResourceManager.GetObject("MapStatistics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Plugin {
            get {
                object obj = ResourceManager.GetObject("Plugin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PluginReload {
            get {
                object obj = ResourceManager.GetObject("PluginReload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileAnimation {
            get {
                object obj = ResourceManager.GetObject("TileAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileAnimationFrameDelete {
            get {
                object obj = ResourceManager.GetObject("TileAnimationFrameDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileAnimationFrameProperties {
            get {
                object obj = ResourceManager.GetObject("TileAnimationFrameProperties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileProperties {
            get {
                object obj = ResourceManager.GetObject("TileProperties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TilePropertiesIndicator {
            get {
                object obj = ResourceManager.GetObject("TilePropertiesIndicator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileSheet {
            get {
                object obj = ResourceManager.GetObject("TileSheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileSheetAutoUpdateDisable {
            get {
                object obj = ResourceManager.GetObject("TileSheetAutoUpdateDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileSheetAutoUpdateEnable {
            get {
                object obj = ResourceManager.GetObject("TileSheetAutoUpdateEnable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileSheetDelete {
            get {
                object obj = ResourceManager.GetObject("TileSheetDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileSheetNew {
            get {
                object obj = ResourceManager.GetObject("TileSheetNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileSheetProperties {
            get {
                object obj = ResourceManager.GetObject("TileSheetProperties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TileSheetRemoveDependencies {
            get {
                object obj = ResourceManager.GetObject("TileSheetRemoveDependencies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsDropper {
            get {
                object obj = ResourceManager.GetObject("ToolsDropper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ToolsDropperCursor {
            get {
                object obj = ResourceManager.GetObject("ToolsDropperCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsEraser {
            get {
                object obj = ResourceManager.GetObject("ToolsEraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ToolsEraserCursor {
            get {
                object obj = ResourceManager.GetObject("ToolsEraserCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsSelect {
            get {
                object obj = ResourceManager.GetObject("ToolsSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsSingleTile {
            get {
                object obj = ResourceManager.GetObject("ToolsSingleTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ToolsSingleTileCursor {
            get {
                object obj = ResourceManager.GetObject("ToolsSingleTileCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsTileBlock {
            get {
                object obj = ResourceManager.GetObject("ToolsTileBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ToolsTileBlockCursor {
            get {
                object obj = ResourceManager.GetObject("ToolsTileBlockCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsTileBrush {
            get {
                object obj = ResourceManager.GetObject("ToolsTileBrush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VewTileGuides {
            get {
                object obj = ResourceManager.GetObject("VewTileGuides", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VewTileGuidesHide {
            get {
                object obj = ResourceManager.GetObject("VewTileGuidesHide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VewTileGuidesShow {
            get {
                object obj = ResourceManager.GetObject("VewTileGuidesShow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View {
            get {
                object obj = ResourceManager.GetObject("View", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewFullScreen {
            get {
                object obj = ResourceManager.GetObject("ViewFullScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewLayerCompositing {
            get {
                object obj = ResourceManager.GetObject("ViewLayerCompositing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewLayerCompositingDimUnselected {
            get {
                object obj = ResourceManager.GetObject("ViewLayerCompositingDimUnselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewLayerCompositingShowAll {
            get {
                object obj = ResourceManager.GetObject("ViewLayerCompositingShowAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewViewport {
            get {
                object obj = ResourceManager.GetObject("ViewViewport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewWindowed {
            get {
                object obj = ResourceManager.GetObject("ViewWindowed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewZoom {
            get {
                object obj = ResourceManager.GetObject("ViewZoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewZoomIn {
            get {
                object obj = ResourceManager.GetObject("ViewZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewZoomOut {
            get {
                object obj = ResourceManager.GetObject("ViewZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
